[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_BACKEND_URL = "https://ecommerce-website-nvw6.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
